CREATE TABLE users (name varchar(255), email varchar(255), age varchar(255));
INSERT INTO users (name, email, age) VALUES ('Raphael Nerd', 'raphael.nerd@example.com', 25);
INSERT INTO users (name, email, age) VALUES ('Wannabe JavaDev', 'wannabe.javadev@example.com', 40);
INSERT INTO users (name, email, age) VALUES ('Alice Wonderland', 'alice.wonderland@example.com', 30);
INSERT INTO users (name, email, age) VALUES ('Bob Builder', 'bob.builder@example.com', 35);
INSERT INTO users (name, email, age) VALUES ('Charlie Chaplin', 'charlie.chaplin@example.com', 50);
INSERT INTO users (name, email, age) VALUES ('Diana Prince', 'diana.prince@example.com', 28);
INSERT INTO users (name, email, age) VALUES ('Edward Scissorhands', 'edward.scissorhands@example.com', 45);
INSERT INTO users (name, email, age) VALUES ('Fiona Apple', 'fiona.apple@example.com', 33);
INSERT INTO users (name, email, age) VALUES ('George Orwell', 'george.orwell@example.com', 55);
INSERT INTO users (name, email, age) VALUES ('Hannah Montana', 'hannah.montana@example.com', 22);
INSERT INTO users (name, email, age) VALUES ('Isaac Newton', 'isaac.newton@example.com', 62);
INSERT INTO users (name, email, age) VALUES ('Jane Austen', 'jane.austen@example.com', 38);
INSERT INTO users (name, email, age) VALUES ('Katherine Johnson', 'katherine.johnson@example.com', 98);
INSERT INTO users (name, email, age) VALUES ('Leonardo da Vinci', 'leonardo.davinci@example.com', 67);
INSERT INTO users (name, email, age) VALUES ('Marie Curie', 'marie.curie@example.com', 66);
INSERT INTO users (name, email, age) VALUES ('Nikola Tesla', 'nikola.tesla@example.com', 86);
INSERT INTO users (name, email, age) VALUES ('Oprah Winfrey', 'oprah.winfrey@example.com', 68);
INSERT INTO users (name, email, age) VALUES ('Pablo Picasso', 'pablo.picasso@example.com', 91);
INSERT INTO users (name, email, age) VALUES ('Queen Elizabeth II', 'queen.elizabeth@example.com', 95);
INSERT INTO users (name, email, age) VALUES ('Richard Feynman', 'richard.feynman@example.com', 69);